/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package J2303;


public class App {
    public static void main(String[] args) {
        Pessoa Lorena = new Pessoa("Lorena", 19, "Feminino");
        Lorena.aprensentarSe();

    }
}
